src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use App\Repository\UserRepository;
use phpDocumentor\Reflection\PseudoTypes\True_;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'user')]

class User implements UserInterface , PasswordAuthenticatedUserInterface , TwoFactorInterface

{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    #[ORM\Column(type: 'integer', nullable: false)]
    private ?int $cin = null;

    public function getCin(): ?int
    {
        return $this->cin;
    }

    public function setCin(int $cin): self
    {
        $this->cin = $cin;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $nom = null;

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $prenom = null;

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false , unique: true)]

    private ?string $email = null;

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $username = null;

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $password = null;

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $role = null;

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $sexe = null;

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $adresse = null;

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;
        return $this;
    }

    #[ORM\Column(type: 'integer', nullable: false)]
    private ?int $numero = null;

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $googleAuthenticatorSecret;


    #[ORM\OneToMany(targetEntity: Promotion::class, mappedBy: 'user')]
    private Collection $promotions;

  

    public function __construct()
    {
        $this->promotions = new ArrayCollection();
        $this->projectTasks = new ArrayCollection();
    }
    


    /**
     * @return Collection<int, Promotion>
     */
    public function getPromotions(): Collection
    {
        if (!$this->promotions instanceof Collection) {
            $this->promotions = new ArrayCollection();
        }
        return $this->promotions;
    }

    public function addPromotion(Promotion $promotion): self
    {
        if (!$this->getPromotions()->contains($promotion)) {
            $this->getPromotions()->add($promotion);
        }
        return $this;
    }

    public function removePromotion(Promotion $promotion): self
    {
        $this->getPromotions()->removeElement($promotion);
        return $this;
    }

    public function getRoles(): array
    {   
        $role = [];
        if($this->role == 'Employe'){
            $role[] = 'ROLE_Employe';
        }
        else if($this->role == 'RHR'){
            $role[] = 'RHR';
        }

        return array_unique($role);
    }

    public function eraseCredentials() : void
    {
        
    }

    public function getUserIdentifier(): string
    {
        return $this->id;
    }
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ProjectTask::class, orphanRemoval: true)]
    private Collection $projectTasks;

 

    /**
     * @return Collection<int, ProjectTask>
     */
    public function getProjectTasks(): Collection
    {
        if (!$this->projectTasks instanceof Collection) {
            $this->projectTasks = new ArrayCollection();
        }
        return $this->projectTasks;
    }

    public function addProjectTask(ProjectTask $projectTask): self
    {
        if (!$this->getProjectTasks()->contains($projectTask)) {
            $this->getProjectTasks()->add($projectTask);
            $projectTask->setUser($this);
        }
        return $this;
    }

    public function removeProjectTask(ProjectTask $projectTask): self
    {
        if ($this->projectTasks->removeElement($projectTask)) {
            // set the owning side to null (unless already changed)
            if ($projectTask->getUser() === $this) {
                $projectTask->setUser(null);
            }
        }
        return $this;
    }


   /////2FA

   public function isGoogleAuthenticatorEnabled(): bool
   {
       return null !== $this->googleAuthenticatorSecret;
   }

   public function getGoogleAuthenticatorUsername(): string
   {
       return $this->username;
   }

   public function getGoogleAuthenticatorSecret(): ?string
   {
       return $this->googleAuthenticatorSecret;
   }

   public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): void
   {
       $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;
   }

   

  


}

src/Controller/LoginController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class LoginController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // Get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // Get the last username entered by the user (email)
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('login/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        // This method can be blank - it will be intercepted by the logout key on your firewall
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/Login/login.html.twig
<html lang="en">
  <head>
    {% block title %}<title>Login 07</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet">

    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <!-- Use asset() for local CSS files -->
    <link rel="stylesheet" href="{{ asset('Login/css/style.css') }}">

    {% endblock %}
  </head>
  <body>
    {% block body %}
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
            <h2 class="heading-section">Login #07</h2>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="wrap d-md-flex">
              <div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
                <div class="text w-100">
                  <h2>Welcome to login</h2>
                  <p>Don't have an account?</p>
                  <a href="{{path('app_register')}}" class="btn btn-white btn-outline-white">Sign Up</a>
                </div>
              </div>
              <div class="login-wrap p-4 p-lg-5">
                {% block login_form %}
                <form method="post">
                    {% if error %}
                        <div class="alert alert-danger">
                            {{ error.messageKey|trans(error.messageData, 'security') }}
                        </div>
                    {% endif %}
                
                    {% if app.user %}
                        <div class="mb-3">
                            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                        </div>
                    {% endif %}
                
                    <h3 class="mb-4">Sign In</h3>
                
                    <label for="email">Email</label>
                    <input type="email" value="{{ last_username }}" name="_email" id="email" class="form-control" autocomplete="email" required autofocus>
                
                    <label for="password">Password</label>
                    <input type="password" name="_password" id="password" class="form-control" autocomplete="current-password" required>
                
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                    
                      <button class="form-control btn btn-primary submit px-3" type="submit">Sign in</button>
                </form>
                <div class="form-group d-md-flex">
		            	<div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div>
									<div class="w-50 text-md-right">
										<a href="{{path('app_forgot_password_request')}}">Forgot Password</a>
									</div>
		            </div>
                {% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% block js %}
    <!-- Use asset() for local JS files -->
    <script src="{{ asset('Login/js/jquery.min.js') }}"></script>
    <script src="{{ asset('Login/js/popper.js') }}"></script>
    <script src="{{ asset('Login/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('Login/js/main.js') }}"></script>
    {% endblock %}
  </body>
  {% endblock %}
</html>